[project]
name = "server-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.1",
    "flask-cors>=6.0.1",
    "optimum>=1.26.1",
    "scipy>=1.16.1",
    "transformers>=4.54.0",
]
